### ISSUE TITLE
Add more info for SPoRT

### ISSUE THREAD

**Issue by DougManuel** [ohri-mhealth/healthculator#4]

**Comment by DougManuel** [comment]
Kasim,
I decided I might as well just add the SPoRT description directly to the Repo. I've created a new branch for this issue. I didn't view the changes in the browser, so might want to test on healthculator.com site.

Please merge this branch if everything looks good.

**Comment by DougManuel** [comment]
Note that I also added an image to the images folder.

**Comment by DougManuel** [comment]
Didn't mean to close this issue yet!

**Comment by kabdulaziz** [comment]
Doug, I've put this file on healthculator.com. The format is slightly different than the other projects in the list so not sure if you have made it like so on purpose or accidental. Please compare with projectbiglife.ca

**Comment by CBjerke** [comment]
I don't think we should have the text wrapping around the image. I think Yulric fixed this when he worked on the healthcare cost calculator...it may be that the revised file wasn't added to healthculator? 
@kabdulaziz can push the revision through with text left justified to the right of the image?

**Comment by DougManuel** [comment]
Sounds good. Not wrapped text on left side of image.

**Comment by kabdulaziz** [comment]
Done
